// Code generated by gen (uowstore typed-unsupported shell); DO NOT EDIT.

package uowstore

import (
	"context"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/types"
	"time"
)

// unsupportedDoltStorage is the generated typed-unsupported shell for storage.DoltStorage.
// Every method returns *storage.ErrUnsupported; embed it and override the
// real slice. DO NOT hand-edit — regenerate with `go generate ./...`.
type unsupportedDoltStorage struct{}

func (unsupportedDoltStorage) CreateIssue(_ context.Context, _ *types.Issue, _ string) (err error) {
	err = errUnsupported("CreateIssue")
	return
}

func (unsupportedDoltStorage) CreateIssues(_ context.Context, _ []*types.Issue, _ string) (err error) {
	err = errUnsupported("CreateIssues")
	return
}

func (unsupportedDoltStorage) GetIssue(_ context.Context, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("GetIssue")
	return
}

func (unsupportedDoltStorage) GetIssueByExternalRef(_ context.Context, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("GetIssueByExternalRef")
	return
}

func (unsupportedDoltStorage) GetIssuesByIDs(_ context.Context, _ []string) (_ []*types.Issue, err error) {
	err = errUnsupported("GetIssuesByIDs")
	return
}

func (unsupportedDoltStorage) UpdateIssue(_ context.Context, _ string, _ map[string]interface{}, _ string) (err error) {
	err = errUnsupported("UpdateIssue")
	return
}

func (unsupportedDoltStorage) ReopenIssue(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("ReopenIssue")
	return
}

func (unsupportedDoltStorage) UpdateIssueType(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("UpdateIssueType")
	return
}

func (unsupportedDoltStorage) CloseIssue(_ context.Context, _ string, _ string, _ string, _ string) (err error) {
	err = errUnsupported("CloseIssue")
	return
}

func (unsupportedDoltStorage) DeleteIssue(_ context.Context, _ string) (err error) {
	err = errUnsupported("DeleteIssue")
	return
}

func (unsupportedDoltStorage) SearchIssues(_ context.Context, _ string, _ types.IssueFilter) (_ []*types.Issue, err error) {
	err = errUnsupported("SearchIssues")
	return
}

func (unsupportedDoltStorage) SearchIssuesWithCounts(_ context.Context, _ string, _ types.IssueFilter) (_ []*types.IssueWithCounts, err error) {
	err = errUnsupported("SearchIssuesWithCounts")
	return
}

func (unsupportedDoltStorage) SearchIssueIDs(_ context.Context, _ string, _ types.IssueFilter) (_ []string, err error) {
	err = errUnsupported("SearchIssueIDs")
	return
}

func (unsupportedDoltStorage) AddDependency(_ context.Context, _ *types.Dependency, _ string) (err error) {
	err = errUnsupported("AddDependency")
	return
}

func (unsupportedDoltStorage) RemoveDependency(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("RemoveDependency")
	return
}

func (unsupportedDoltStorage) GetDependencies(_ context.Context, _ string) (_ []*types.Issue, err error) {
	err = errUnsupported("GetDependencies")
	return
}

func (unsupportedDoltStorage) GetDependents(_ context.Context, _ string) (_ []*types.Issue, err error) {
	err = errUnsupported("GetDependents")
	return
}

func (unsupportedDoltStorage) GetDependenciesWithMetadata(_ context.Context, _ string) (_ []*types.IssueWithDependencyMetadata, err error) {
	err = errUnsupported("GetDependenciesWithMetadata")
	return
}

func (unsupportedDoltStorage) GetDependentsWithMetadata(_ context.Context, _ string) (_ []*types.IssueWithDependencyMetadata, err error) {
	err = errUnsupported("GetDependentsWithMetadata")
	return
}

func (unsupportedDoltStorage) GetDependencyTree(_ context.Context, _ string, _ int, _ bool, _ bool) (_ []*types.TreeNode, err error) {
	err = errUnsupported("GetDependencyTree")
	return
}

func (unsupportedDoltStorage) AddLabel(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("AddLabel")
	return
}

func (unsupportedDoltStorage) RemoveLabel(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("RemoveLabel")
	return
}

func (unsupportedDoltStorage) GetLabels(_ context.Context, _ string) (_ []string, err error) {
	err = errUnsupported("GetLabels")
	return
}

func (unsupportedDoltStorage) GetIssuesByLabel(_ context.Context, _ string) (_ []*types.Issue, err error) {
	err = errUnsupported("GetIssuesByLabel")
	return
}

func (unsupportedDoltStorage) GetReadyWork(_ context.Context, _ types.WorkFilter) (_ []*types.Issue, err error) {
	err = errUnsupported("GetReadyWork")
	return
}

func (unsupportedDoltStorage) GetReadyWorkWithCounts(_ context.Context, _ types.WorkFilter) (_ []*types.IssueWithCounts, err error) {
	err = errUnsupported("GetReadyWorkWithCounts")
	return
}

func (unsupportedDoltStorage) GetBlockedIssues(_ context.Context, _ types.WorkFilter) (_ []*types.BlockedIssue, err error) {
	err = errUnsupported("GetBlockedIssues")
	return
}

func (unsupportedDoltStorage) GetEpicsEligibleForClosure(_ context.Context) (_ []*types.EpicStatus, err error) {
	err = errUnsupported("GetEpicsEligibleForClosure")
	return
}

func (unsupportedDoltStorage) ListWisps(_ context.Context, _ types.WispFilter) (_ []*types.Issue, err error) {
	err = errUnsupported("ListWisps")
	return
}

func (unsupportedDoltStorage) AddIssueComment(_ context.Context, _ string, _ string, _ string) (_ *types.Comment, err error) {
	err = errUnsupported("AddIssueComment")
	return
}

func (unsupportedDoltStorage) GetIssueComments(_ context.Context, _ string) (_ []*types.Comment, err error) {
	err = errUnsupported("GetIssueComments")
	return
}

func (unsupportedDoltStorage) GetEvents(_ context.Context, _ string, _ int) (_ []*types.Event, err error) {
	err = errUnsupported("GetEvents")
	return
}

func (unsupportedDoltStorage) GetAllEventsSince(_ context.Context, _ time.Time) (_ []*types.Event, err error) {
	err = errUnsupported("GetAllEventsSince")
	return
}

func (unsupportedDoltStorage) CountIssues(_ context.Context, _ string, _ types.IssueFilter) (_ int64, err error) {
	err = errUnsupported("CountIssues")
	return
}

func (unsupportedDoltStorage) CountIssuesByGroup(_ context.Context, _ types.IssueFilter, _ string) (_ map[string]int, err error) {
	err = errUnsupported("CountIssuesByGroup")
	return
}

func (unsupportedDoltStorage) CountDependents(_ context.Context, _ string) (_ int64, err error) {
	err = errUnsupported("CountDependents")
	return
}

func (unsupportedDoltStorage) CountDependencies(_ context.Context, _ string) (_ int64, err error) {
	err = errUnsupported("CountDependencies")
	return
}

func (unsupportedDoltStorage) CountIssueComments(_ context.Context, _ string) (_ int64, err error) {
	err = errUnsupported("CountIssueComments")
	return
}

func (unsupportedDoltStorage) CountEvents(_ context.Context, _ string, _ int) (_ int64, err error) {
	err = errUnsupported("CountEvents")
	return
}

func (unsupportedDoltStorage) IterIssues(_ context.Context, _ string, _ types.IssueFilter) (_ storage.Iter[types.Issue], err error) {
	err = errUnsupported("IterIssues")
	return
}

func (unsupportedDoltStorage) IterDependentsWithMetadata(_ context.Context, _ string) (_ storage.Iter[types.IssueWithDependencyMetadata], err error) {
	err = errUnsupported("IterDependentsWithMetadata")
	return
}

func (unsupportedDoltStorage) IterDependenciesWithMetadata(_ context.Context, _ string) (_ storage.Iter[types.IssueWithDependencyMetadata], err error) {
	err = errUnsupported("IterDependenciesWithMetadata")
	return
}

func (unsupportedDoltStorage) IterIssueComments(_ context.Context, _ string) (_ storage.Iter[types.Comment], err error) {
	err = errUnsupported("IterIssueComments")
	return
}

func (unsupportedDoltStorage) IterEvents(_ context.Context, _ string, _ int) (_ storage.Iter[types.Event], err error) {
	err = errUnsupported("IterEvents")
	return
}

func (unsupportedDoltStorage) IterAllEventsSince(_ context.Context, _ time.Time) (_ storage.Iter[types.Event], err error) {
	err = errUnsupported("IterAllEventsSince")
	return
}

func (unsupportedDoltStorage) IterReadyWork(_ context.Context, _ types.WorkFilter) (_ storage.Iter[types.Issue], err error) {
	err = errUnsupported("IterReadyWork")
	return
}

func (unsupportedDoltStorage) IterBlockedIssues(_ context.Context, _ types.WorkFilter) (_ storage.Iter[types.BlockedIssue], err error) {
	err = errUnsupported("IterBlockedIssues")
	return
}

func (unsupportedDoltStorage) IterWisps(_ context.Context, _ types.WispFilter) (_ storage.Iter[types.Issue], err error) {
	err = errUnsupported("IterWisps")
	return
}

func (unsupportedDoltStorage) GetStatistics(_ context.Context) (_ *types.Statistics, err error) {
	err = errUnsupported("GetStatistics")
	return
}

func (unsupportedDoltStorage) SetConfig(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("SetConfig")
	return
}

func (unsupportedDoltStorage) GetConfig(_ context.Context, _ string) (_ string, err error) {
	err = errUnsupported("GetConfig")
	return
}

func (unsupportedDoltStorage) GetAllConfig(_ context.Context) (_ map[string]string, err error) {
	err = errUnsupported("GetAllConfig")
	return
}

func (unsupportedDoltStorage) SetLocalMetadata(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("SetLocalMetadata")
	return
}

func (unsupportedDoltStorage) GetLocalMetadata(_ context.Context, _ string) (_ string, err error) {
	err = errUnsupported("GetLocalMetadata")
	return
}

func (unsupportedDoltStorage) RunInTransaction(_ context.Context, _ string, _ func(tx storage.Transaction) error) (err error) {
	err = errUnsupported("RunInTransaction")
	return
}

func (unsupportedDoltStorage) MergeSlotCreate(_ context.Context, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("MergeSlotCreate")
	return
}

func (unsupportedDoltStorage) MergeSlotCheck(_ context.Context) (_ *storage.MergeSlotStatus, err error) {
	err = errUnsupported("MergeSlotCheck")
	return
}

func (unsupportedDoltStorage) MergeSlotAcquire(_ context.Context, _ string, _ string, _ bool) (_ *storage.MergeSlotResult, err error) {
	err = errUnsupported("MergeSlotAcquire")
	return
}

func (unsupportedDoltStorage) MergeSlotRelease(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("MergeSlotRelease")
	return
}

func (unsupportedDoltStorage) SlotSet(_ context.Context, _ string, _ string, _ string, _ string) (err error) {
	err = errUnsupported("SlotSet")
	return
}

func (unsupportedDoltStorage) SlotGet(_ context.Context, _ string, _ string) (_ string, err error) {
	err = errUnsupported("SlotGet")
	return
}

func (unsupportedDoltStorage) SlotClear(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("SlotClear")
	return
}

func (unsupportedDoltStorage) Close() (err error) {
	err = errUnsupported("Close")
	return
}

func (unsupportedDoltStorage) Branch(_ context.Context, _ string) (err error) {
	err = errUnsupported("Branch")
	return
}

func (unsupportedDoltStorage) Checkout(_ context.Context, _ string) (err error) {
	err = errUnsupported("Checkout")
	return
}

func (unsupportedDoltStorage) CurrentBranch(_ context.Context) (_ string, err error) {
	err = errUnsupported("CurrentBranch")
	return
}

func (unsupportedDoltStorage) DeleteBranch(_ context.Context, _ string) (err error) {
	err = errUnsupported("DeleteBranch")
	return
}

func (unsupportedDoltStorage) ListBranches(_ context.Context) (_ []string, err error) {
	err = errUnsupported("ListBranches")
	return
}

func (unsupportedDoltStorage) Commit(_ context.Context, _ string) (err error) {
	err = errUnsupported("Commit")
	return
}

func (unsupportedDoltStorage) CommitWithConfig(_ context.Context, _ string) (err error) {
	err = errUnsupported("CommitWithConfig")
	return
}

func (unsupportedDoltStorage) CommitMergeResolution(_ context.Context, _ string) (err error) {
	err = errUnsupported("CommitMergeResolution")
	return
}

func (unsupportedDoltStorage) CommitPending(_ context.Context, _ string) (_ bool, err error) {
	err = errUnsupported("CommitPending")
	return
}

func (unsupportedDoltStorage) CommitExists(_ context.Context, _ string) (_ bool, err error) {
	err = errUnsupported("CommitExists")
	return
}

func (unsupportedDoltStorage) GetCurrentCommit(_ context.Context) (_ string, err error) {
	err = errUnsupported("GetCurrentCommit")
	return
}

func (unsupportedDoltStorage) Status(_ context.Context) (_ *storage.Status, err error) {
	err = errUnsupported("Status")
	return
}

func (unsupportedDoltStorage) Log(_ context.Context, _ int) (_ []storage.CommitInfo, err error) {
	err = errUnsupported("Log")
	return
}

func (unsupportedDoltStorage) Merge(_ context.Context, _ string) (_ []storage.Conflict, err error) {
	err = errUnsupported("Merge")
	return
}

func (unsupportedDoltStorage) GetConflicts(_ context.Context) (_ []storage.Conflict, err error) {
	err = errUnsupported("GetConflicts")
	return
}

func (unsupportedDoltStorage) ResolveConflicts(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("ResolveConflicts")
	return
}

func (unsupportedDoltStorage) History(_ context.Context, _ string) (_ []*storage.HistoryEntry, err error) {
	err = errUnsupported("History")
	return
}

func (unsupportedDoltStorage) AsOf(_ context.Context, _ string, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("AsOf")
	return
}

func (unsupportedDoltStorage) Diff(_ context.Context, _ string, _ string) (_ []*storage.DiffEntry, err error) {
	err = errUnsupported("Diff")
	return
}

func (unsupportedDoltStorage) AddRemote(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("AddRemote")
	return
}

func (unsupportedDoltStorage) RemoveRemote(_ context.Context, _ string) (err error) {
	err = errUnsupported("RemoveRemote")
	return
}

func (unsupportedDoltStorage) HasRemote(_ context.Context, _ string) (_ bool, err error) {
	err = errUnsupported("HasRemote")
	return
}

func (unsupportedDoltStorage) ListRemotes(_ context.Context) (_ []storage.RemoteInfo, err error) {
	err = errUnsupported("ListRemotes")
	return
}

func (unsupportedDoltStorage) Push(_ context.Context) (err error) {
	err = errUnsupported("Push")
	return
}

func (unsupportedDoltStorage) Pull(_ context.Context) (err error) {
	err = errUnsupported("Pull")
	return
}

func (unsupportedDoltStorage) ForcePush(_ context.Context) (err error) {
	err = errUnsupported("ForcePush")
	return
}

func (unsupportedDoltStorage) PushRemote(_ context.Context, _ string, _ bool) (err error) {
	err = errUnsupported("PushRemote")
	return
}

func (unsupportedDoltStorage) PullRemote(_ context.Context, _ string) (err error) {
	err = errUnsupported("PullRemote")
	return
}

func (unsupportedDoltStorage) Fetch(_ context.Context, _ string) (err error) {
	err = errUnsupported("Fetch")
	return
}

func (unsupportedDoltStorage) PushTo(_ context.Context, _ string) (err error) {
	err = errUnsupported("PushTo")
	return
}

func (unsupportedDoltStorage) PullFrom(_ context.Context, _ string) (_ []storage.Conflict, err error) {
	err = errUnsupported("PullFrom")
	return
}

func (unsupportedDoltStorage) Sync(_ context.Context, _ string, _ string) (_ *storage.SyncResult, err error) {
	err = errUnsupported("Sync")
	return
}

func (unsupportedDoltStorage) SyncStatus(_ context.Context, _ string) (_ *storage.SyncStatus, err error) {
	err = errUnsupported("SyncStatus")
	return
}

func (unsupportedDoltStorage) AddFederationPeer(_ context.Context, _ *storage.FederationPeer) (err error) {
	err = errUnsupported("AddFederationPeer")
	return
}

func (unsupportedDoltStorage) GetFederationPeer(_ context.Context, _ string) (_ *storage.FederationPeer, err error) {
	err = errUnsupported("GetFederationPeer")
	return
}

func (unsupportedDoltStorage) ListFederationPeers(_ context.Context) (_ []*storage.FederationPeer, err error) {
	err = errUnsupported("ListFederationPeers")
	return
}

func (unsupportedDoltStorage) RemoveFederationPeer(_ context.Context, _ string) (err error) {
	err = errUnsupported("RemoveFederationPeer")
	return
}

func (unsupportedDoltStorage) CreateIssuesWithFullOptions(_ context.Context, _ []*types.Issue, _ string, _ storage.BatchCreateOptions) (err error) {
	err = errUnsupported("CreateIssuesWithFullOptions")
	return
}

func (unsupportedDoltStorage) DeleteIssues(_ context.Context, _ []string, _ bool, _ bool, _ bool) (_ *types.DeleteIssuesResult, err error) {
	err = errUnsupported("DeleteIssues")
	return
}

func (unsupportedDoltStorage) DeleteIssuesBySourceRepo(_ context.Context, _ string) (_ int, err error) {
	err = errUnsupported("DeleteIssuesBySourceRepo")
	return
}

func (unsupportedDoltStorage) UpdateIssueID(_ context.Context, _ string, _ string, _ *types.Issue, _ string) (err error) {
	err = errUnsupported("UpdateIssueID")
	return
}

func (unsupportedDoltStorage) ClaimIssue(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("ClaimIssue")
	return
}

func (unsupportedDoltStorage) ClaimReadyIssue(_ context.Context, _ types.WorkFilter, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("ClaimReadyIssue")
	return
}

func (unsupportedDoltStorage) HeartbeatIssue(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("HeartbeatIssue")
	return
}

func (unsupportedDoltStorage) ReclaimExpiredLeases(_ context.Context, _ time.Duration, _ string) (_ []types.ReclaimedLease, err error) {
	err = errUnsupported("ReclaimExpiredLeases")
	return
}

func (unsupportedDoltStorage) PromoteFromEphemeral(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("PromoteFromEphemeral")
	return
}

func (unsupportedDoltStorage) GetNextChildID(_ context.Context, _ string) (_ string, err error) {
	err = errUnsupported("GetNextChildID")
	return
}

func (unsupportedDoltStorage) GetDependencyRecords(_ context.Context, _ string) (_ []*types.Dependency, err error) {
	err = errUnsupported("GetDependencyRecords")
	return
}

func (unsupportedDoltStorage) GetDependencyRecordsForIssues(_ context.Context, _ []string) (_ map[string][]*types.Dependency, err error) {
	err = errUnsupported("GetDependencyRecordsForIssues")
	return
}

func (unsupportedDoltStorage) GetDependentRecords(_ context.Context, _ string, _ string, _ int, _ string) (_ []*types.Dependency, err error) {
	err = errUnsupported("GetDependentRecords")
	return
}

func (unsupportedDoltStorage) CountDependentRecords(_ context.Context, _ string, _ string) (_ int, err error) {
	err = errUnsupported("CountDependentRecords")
	return
}

func (unsupportedDoltStorage) GetAllDependencyRecords(_ context.Context) (_ map[string][]*types.Dependency, err error) {
	err = errUnsupported("GetAllDependencyRecords")
	return
}

func (unsupportedDoltStorage) GetDependencyCounts(_ context.Context, _ []string) (_ map[string]*types.DependencyCounts, err error) {
	err = errUnsupported("GetDependencyCounts")
	return
}

func (unsupportedDoltStorage) GetBlockingInfoForIssues(_ context.Context, _ []string) (_ map[string][]string, _ map[string][]string, _ map[string]string, err error) {
	err = errUnsupported("GetBlockingInfoForIssues")
	return
}

func (unsupportedDoltStorage) IsBlocked(_ context.Context, _ string) (_ bool, _ []string, err error) {
	err = errUnsupported("IsBlocked")
	return
}

func (unsupportedDoltStorage) IsBlockedBatch(_ context.Context, _ []string) (_ map[string]bool, err error) {
	err = errUnsupported("IsBlockedBatch")
	return
}

func (unsupportedDoltStorage) GetNewlyUnblockedByClose(_ context.Context, _ string) (_ []*types.Issue, err error) {
	err = errUnsupported("GetNewlyUnblockedByClose")
	return
}

func (unsupportedDoltStorage) DetectCycles(_ context.Context) (_ [][]*types.Issue, err error) {
	err = errUnsupported("DetectCycles")
	return
}

func (unsupportedDoltStorage) FindWispDependentsRecursive(_ context.Context, _ []string) (_ map[string]bool, err error) {
	err = errUnsupported("FindWispDependentsRecursive")
	return
}

func (unsupportedDoltStorage) IterAllDependencyRecords(_ context.Context) (_ storage.Iter[types.Dependency], err error) {
	err = errUnsupported("IterAllDependencyRecords")
	return
}

func (unsupportedDoltStorage) CountDependentsByStatus(_ context.Context, _ string, _ types.Status) (_ int64, err error) {
	err = errUnsupported("CountDependentsByStatus")
	return
}

func (unsupportedDoltStorage) EventsSince(_ context.Context, _ storage.EventCursor, _ string, _ int) (_ []*types.Event, err error) {
	err = errUnsupported("EventsSince")
	return
}

func (unsupportedDoltStorage) AddComment(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("AddComment")
	return
}

func (unsupportedDoltStorage) ImportIssueComment(_ context.Context, _ string, _ string, _ string, _ time.Time) (_ *types.Comment, err error) {
	err = errUnsupported("ImportIssueComment")
	return
}

func (unsupportedDoltStorage) GetCommentCounts(_ context.Context, _ []string) (_ map[string]int, err error) {
	err = errUnsupported("GetCommentCounts")
	return
}

func (unsupportedDoltStorage) GetCommentsForIssues(_ context.Context, _ []string) (_ map[string][]*types.Comment, err error) {
	err = errUnsupported("GetCommentsForIssues")
	return
}

func (unsupportedDoltStorage) GetLabelsForIssues(_ context.Context, _ []string) (_ map[string][]string, err error) {
	err = errUnsupported("GetLabelsForIssues")
	return
}

func (unsupportedDoltStorage) GetMetadata(_ context.Context, _ string) (_ string, err error) {
	err = errUnsupported("GetMetadata")
	return
}

func (unsupportedDoltStorage) SetMetadata(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("SetMetadata")
	return
}

func (unsupportedDoltStorage) DeleteConfig(_ context.Context, _ string) (err error) {
	err = errUnsupported("DeleteConfig")
	return
}

func (unsupportedDoltStorage) GetCustomStatuses(_ context.Context) (_ []string, err error) {
	err = errUnsupported("GetCustomStatuses")
	return
}

func (unsupportedDoltStorage) GetCustomStatusesDetailed(_ context.Context) (_ []types.CustomStatus, err error) {
	err = errUnsupported("GetCustomStatusesDetailed")
	return
}

func (unsupportedDoltStorage) GetCustomTypes(_ context.Context) (_ []string, err error) {
	err = errUnsupported("GetCustomTypes")
	return
}

func (unsupportedDoltStorage) GetInfraTypes(_ context.Context) (_ map[string]bool) {
	// NOTE: no error channel on this signature; returns the zero value.
	return
}

func (unsupportedDoltStorage) IsInfraTypeCtx(_ context.Context, _ types.IssueType) (_ bool) {
	// NOTE: no error channel on this signature; returns the zero value.
	return
}

func (unsupportedDoltStorage) CheckEligibility(_ context.Context, _ string, _ int) (_ bool, _ string, err error) {
	err = errUnsupported("CheckEligibility")
	return
}

func (unsupportedDoltStorage) ApplyCompaction(_ context.Context, _ string, _ int, _ int, _ int, _ string) (err error) {
	err = errUnsupported("ApplyCompaction")
	return
}

func (unsupportedDoltStorage) GetTier1Candidates(_ context.Context) (_ []*types.CompactionCandidate, err error) {
	err = errUnsupported("GetTier1Candidates")
	return
}

func (unsupportedDoltStorage) GetTier2Candidates(_ context.Context) (_ []*types.CompactionCandidate, err error) {
	err = errUnsupported("GetTier2Candidates")
	return
}

func (unsupportedDoltStorage) SnapshotIssue(_ context.Context, _ string, _ int) (err error) {
	err = errUnsupported("SnapshotIssue")
	return
}

func (unsupportedDoltStorage) GetCompactionSnapshot(_ context.Context, _ string) (_ *types.IssueSnapshot, err error) {
	err = errUnsupported("GetCompactionSnapshot")
	return
}

func (unsupportedDoltStorage) RestoreFromSnapshot(_ context.Context, _ string) (_ *types.IssueSnapshot, err error) {
	err = errUnsupported("RestoreFromSnapshot")
	return
}

func (unsupportedDoltStorage) GetRepoMtime(_ context.Context, _ string) (_ int64, err error) {
	err = errUnsupported("GetRepoMtime")
	return
}

func (unsupportedDoltStorage) SetRepoMtime(_ context.Context, _ string, _ string, _ int64) (err error) {
	err = errUnsupported("SetRepoMtime")
	return
}

func (unsupportedDoltStorage) ClearRepoMtime(_ context.Context, _ string) (err error) {
	err = errUnsupported("ClearRepoMtime")
	return
}

func (unsupportedDoltStorage) GetMoleculeProgress(_ context.Context, _ string) (_ *types.MoleculeProgressStats, err error) {
	err = errUnsupported("GetMoleculeProgress")
	return
}

func (unsupportedDoltStorage) GetMoleculeLastActivity(_ context.Context, _ string) (_ *types.MoleculeLastActivity, err error) {
	err = errUnsupported("GetMoleculeLastActivity")
	return
}

func (unsupportedDoltStorage) GetStaleIssues(_ context.Context, _ types.StaleFilter) (_ []*types.Issue, err error) {
	err = errUnsupported("GetStaleIssues")
	return
}

var _ storage.DoltStorage = unsupportedDoltStorage{}

// unsupportedTransaction is the generated typed-unsupported shell for storage.Transaction.
// Every method returns *storage.ErrUnsupported; embed it and override the
// real slice. DO NOT hand-edit — regenerate with `go generate ./...`.
type unsupportedTransaction struct{}

func (unsupportedTransaction) CreateIssue(_ context.Context, _ *types.Issue, _ string) (err error) {
	err = errUnsupported("Transaction.CreateIssue")
	return
}

func (unsupportedTransaction) CreateIssues(_ context.Context, _ []*types.Issue, _ string) (err error) {
	err = errUnsupported("Transaction.CreateIssues")
	return
}

func (unsupportedTransaction) UpdateIssue(_ context.Context, _ string, _ map[string]interface{}, _ string) (err error) {
	err = errUnsupported("Transaction.UpdateIssue")
	return
}

func (unsupportedTransaction) CloseIssue(_ context.Context, _ string, _ string, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.CloseIssue")
	return
}

func (unsupportedTransaction) DeleteIssue(_ context.Context, _ string) (err error) {
	err = errUnsupported("Transaction.DeleteIssue")
	return
}

func (unsupportedTransaction) GetIssue(_ context.Context, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("Transaction.GetIssue")
	return
}

func (unsupportedTransaction) SearchIssues(_ context.Context, _ string, _ types.IssueFilter) (_ []*types.Issue, err error) {
	err = errUnsupported("Transaction.SearchIssues")
	return
}

func (unsupportedTransaction) SearchIssueIDs(_ context.Context, _ string, _ types.IssueFilter) (_ []string, err error) {
	err = errUnsupported("Transaction.SearchIssueIDs")
	return
}

func (unsupportedTransaction) AddDependency(_ context.Context, _ *types.Dependency, _ string) (err error) {
	err = errUnsupported("Transaction.AddDependency")
	return
}

func (unsupportedTransaction) AddDependencyWithOptions(_ context.Context, _ *types.Dependency, _ string, _ storage.DependencyAddOptions) (err error) {
	err = errUnsupported("Transaction.AddDependencyWithOptions")
	return
}

func (unsupportedTransaction) RemoveDependency(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.RemoveDependency")
	return
}

func (unsupportedTransaction) GetDependencyRecords(_ context.Context, _ string) (_ []*types.Dependency, err error) {
	err = errUnsupported("Transaction.GetDependencyRecords")
	return
}

func (unsupportedTransaction) CycleThroughEdges(_ context.Context, _ [][2]string) (_ string, err error) {
	err = errUnsupported("Transaction.CycleThroughEdges")
	return
}

func (unsupportedTransaction) AddLabel(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.AddLabel")
	return
}

func (unsupportedTransaction) RemoveLabel(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.RemoveLabel")
	return
}

func (unsupportedTransaction) GetLabels(_ context.Context, _ string) (_ []string, err error) {
	err = errUnsupported("Transaction.GetLabels")
	return
}

func (unsupportedTransaction) SetConfig(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.SetConfig")
	return
}

func (unsupportedTransaction) GetConfig(_ context.Context, _ string) (_ string, err error) {
	err = errUnsupported("Transaction.GetConfig")
	return
}

func (unsupportedTransaction) SetMetadata(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.SetMetadata")
	return
}

func (unsupportedTransaction) GetMetadata(_ context.Context, _ string) (_ string, err error) {
	err = errUnsupported("Transaction.GetMetadata")
	return
}

func (unsupportedTransaction) SetLocalMetadata(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.SetLocalMetadata")
	return
}

func (unsupportedTransaction) GetLocalMetadata(_ context.Context, _ string) (_ string, err error) {
	err = errUnsupported("Transaction.GetLocalMetadata")
	return
}

func (unsupportedTransaction) AddComment(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("Transaction.AddComment")
	return
}

func (unsupportedTransaction) ImportIssueComment(_ context.Context, _ string, _ string, _ string, _ time.Time) (_ *types.Comment, err error) {
	err = errUnsupported("Transaction.ImportIssueComment")
	return
}

func (unsupportedTransaction) GetIssueComments(_ context.Context, _ string) (_ []*types.Comment, err error) {
	err = errUnsupported("Transaction.GetIssueComments")
	return
}

var _ storage.Transaction = unsupportedTransaction{}
